#**Tuple**

The most important difference from the list is that the tuple is immutable. **Therefore, methods like append() or remove() do not exist in the operations of this type.**

Tuples are commonly used for small collections of values that will not need to change, such as an IP address and port. If we have unchanged data, we should choose tuples because it is much faster than lists.

**We used square brackets üëâüèª'[]' to define the lists. In the tuple, normal parentheses üëâüèª'()'** are used.

The same indexing rules for lists also apply to tuples. Tuples can also be nested and the values can be any valid Python valid.

A tuple is a collection which is ordered and **unchangeable**.

**Tuple Items**

Tuple items are ordered, unchangeable, and allow duplicate values.

Tuple items are **indexed**, the first item has index [0], the second item has index [1] etc.

- **Ordered**
When we say that lists are ordered, it means that the items have a defined order, and that order will not change.

- **Unchangeable**
Tuples are unchangeable, meaning that we cannot change, add or remove items after the tuple has been created.

- **Allow Duplicates**
Since tuples are indexed, tuples can have items with the same value:

**Python Collections (Arrays)**

There are four collection data types in the Python programming language:

- **List** is a collection which is **ordered** and **changeable**. Allows duplicate members.
- **Tuple** is a collection which is **ordered** and **unchangeable**. Allows duplicate members.
- **Set** is a collection which is **unordered** and **unindexed**. No duplicate members.
- **Dictionary** is a collection which is **ordered** and **changeable**. No duplicate members.

**As of Python version 3.7**, dictionaries are ordered. In Python 3.6 and earlier, dictionaries are unordered.

In [ ]:
empty_tuple = ()
print(type(empty_tuple))

try_tuple = ('love')
print(try_tuple)
print(type(try_tuple)) # it's not tuple type.


try_tuple = ('love',)   # It occurs in only single element tuples and we can fix the problem \
print(try_tuple)            # using comma at the end of the element.
print(type(try_tuple)) # it's a tuple type.

<class 'tuple'>
love
<class 'str'>
('love',)
<class 'tuple'>

In [1]:
#Actually, if your tuple contains more than one element, \
# separating elements with commas will be enough.

planets = 'mercury', 'jupiter', 'saturn'   
print(planets)                              
print(type(planets))

print("##############################")



# The tuple() Constructor
# It is also possible to use the tuple() constructor to make a tuple
empty_tuple_1 = tuple()
print(empty_tuple_1)
print(type(empty_tuple_1))

print("################################")

my_tuple = (1, 4, 3, 4, 5, 6, 7, 4)
my_list = list(my_tuple)
print(type(my_list), my_list)

print("#################################")

my_list = [1, 4, 3, 4, 5, 6, 7, 4]
my_tuple = tuple(my_list)
print(type(my_tuple), my_tuple)

('mercury', 'jupiter', 'saturn')
<class 'tuple'>
##############################
()
<class 'tuple'>
################################
<class 'list'> [1, 4, 3, 4, 5, 6, 7, 4]
#################################
<class 'tuple'> (1, 4, 3, 4, 5, 6, 7, 4)

In [ ]:
mountain = tuple('Alps')    # An iterable string can be converted to a tuple :
print(mountain)

('A', 'l', 'p', 's')

**How can We Use a Tuple ?**

If you want, let's take a look at the common features of the list and tuple. So you can have an idea of what to do with tuples.

Both lists and tuples are ordered. It means that when storing elements to these containers, you can sure that their order will remain the same. You can also duplicate values or mix different data types in tuples.

In [ ]:
# Access Tuple Items
mix_value_tuple = (0, 'bird', 3.14, True)

print(len(mix_value_tuple))

print()

even_no = (0, 2, 4)
print(even_no[0])    
print(even_no[1])    
print(even_no[2])   
print(even_no[3])

In [ ]:
thistuple = ("apple", "banana", "cherry", "orange", "kiwi", "melon", "mango")
print(thistuple[-4:-1])

In [ ]:
# Check if Item Exists

thistuple = ("apple", "banana", "cherry")
if "apple" in thistuple:
  print("Yes, 'apple' is in the fruits tuple")

In [7]:
# Change Tuple Values

city_tuple = ('Tokyo', 'Istanbul', 'Moskow', 'Dublin')

city_list = list(city_tuple)
city_list[0] = 'New York'  
city_tuple = tuple(city_list)
print(city_tuple)

('New York', 'Istanbul', 'Moskow', 'Dublin')

In [ ]:
# Add Items

# Once a tuple is created, you cannot add items to it. 
# you can convert it into a list, add your item(s), and 
# convert it back into a tuple

thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.append("orange")
thistuple = tuple(y)

In [ ]:
# Remove Items 

# Tuples are unchangeable, so you cannot remove items from it, 
# but you can use the same workaround as we used for changing and 
# adding tuple items:

thistuple = ("apple", "banana", "cherry")
y = list(thistuple)
y.remove("apple")
thistuple = tuple(y)


# Or you can delete the tuple completely

thistuple = ("apple", "banana", "cherry")
del thistuple
print(thistuple) #this will raise an error because the tuple no longer exists

In [ ]:
# Unpacking a Tuple

# When we create a tuple, we normally assign values to it. 
# This is called "packing" a tuple.

# But, in Python, we are also allowed to extract the values 
# back into variables. This is called "unpacking".

fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

# Note: The number of variables must match the number of values in the tuple, 
# if not, you must use an asterix to collect the remaining values as a list.

In [ ]:
# Using Asterisk*

# If the number of variables is less than the number of values, you can 
# add an * to the variable name and the values will be assigned to the 
# variable as a list:

fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)


# If the asterix is added to another variable name than the last, 
# Python will assign values to the variable until the number of values 
# left matches the number of variables left.

fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

In [ ]:
# Loop Through a Tuple

thistuple = ("apple", "banana", "cherry")
for x in thistuple:
  print(x)


thistuple = ("apple", "banana", "cherry")
for i in range(len(thistuple)):
  print(thistuple[i])



# While Looping

thistuple = ("apple", "banana", "cherry")
i = 0
while i < len(thistuple):
  print(thistuple[i])
  i = i + 1

In [13]:
# Join Two Tuples
tuple1 = ("a", "b", "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2
print(tuple3)


# Multiply Tuples
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 2

print(mytuple)

('a', 'b', 'c', 1, 2, 3)
('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')

**Tuple Methods**

Python has two built-in methods that you can use on tuples.

![image.png]()

**Benefits of Immutability**

Let's take a look at the basic advantages of tuples :

1- *Tuples are faster and more powerful in-memory than lists. You should give it a thought whenever you need to deal with large amounts of data. If you don't want to change your data you may have to choose tuples*.

2- *Because of its immutability, the data stored in a tuple can not be altered by mistake*.

3- *A tuple can be used as a dictionary (we will see in the next lesson) key, while 'TypeError' can result in lists as keys. And this is the usefulness of tuples in the data processing.*

#**Examples**

In [ ]:
fruits = ['Apples', 'Oranges', 'Bananas']
quantities = [5, 3, 4]
prices = [1.50, 2.25, 0.89]
i = 0
output = []
for fruit in fruits:
    temp_qty = quantities[i]
    temp_price = prices[i]
    output.append((fruit, temp_qty, temp_price))
i += 1
print(output)

[('Apples', 5, 1.5), ('Oranges', 5, 1.5), ('Bananas', 5, 1.5)]

In [ ]:
fruits = ['Apples', 'Oranges', 'Bananas']
quantities = [5, 3, 4]
prices = [1.50, 2.25, 0.89]
output=[]
fruit_tuple_0 = (fruits[0], quantities[0], prices[0])
output.append(output)
fruit_tuple_1 = (fruits[1], quantities[1], prices[1])
output.append(output)
fruit_tuple_2 = (fruits[2], quantities[2], prices[2])
output.append(output)
print(fruit_tuple_0, fruit_tuple_1, fruit_tuple_2)

('Apples', 5, 1.5) ('Oranges', 3, 2.25) ('Bananas', 4, 0.89)

In [22]:
fruits = ('Apples', 'Oranges', 'Bananas', 'Kiwi')
quantities = (5, 3, 4)
prices = (1.50, 2.25, 0.89)
groceries = zip(fruits, quantities, prices)  #zip function
print(list(groceries))

[('Apples', 5, 1.5), ('Oranges', 3, 2.25), ('Bananas', 4, 0.89)]

In [ ]:
count, fruit, price = (2, 'apple', 3.5)   # Tuple unpacking !!!.....
print(count)
print(fruit)
print(price)

In [ ]:
city_tuple = ('Tokyo', 'Istanbul', 'Moskow', 'Dublin', 'Tokyo')

print(city_tuple.index("Tokyo"))      # .index() and .count() functions
print(city_tuple.count("Tokyo"))